# Site settings
title: Nothing to see here
#email: your-email@domain.com
description: ""
baseurl: ""
#url: "http://yourdomain.com"
twitter_username: IngmarStein
github_username:  IngmarStein

# Build settings
markdown: kramdown
permalink: pretty
